version: "3.7"

services:
  excursaoapp-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: excursaoapp-sqlserver
    hostname: excursaoapp-sqlserver
    environment:
      SA_PASSWORD: "excursao@app123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "excursao@app123" -Q "SELECT 1" -b -o /dev/null
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
    ports:
      - "1434:1433"
    volumes:
      - ./gestao-backup:/gestao-backup
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets